#!/bin/sh

PNAME=venneuler
SWD=`pwd`
VER=`awk -v ORS= '/Version:/ { print $2 }' DESCRIPTION`
echo "Removing previous dist ..."
rm -rf /tmp/${PNAME}
echo "Copying package base ..."
cp -r ../${PNAME} /tmp

rm -f /tmp/${PNAME}/mkdist

cd /tmp/${PNAME}

echo "Removing CVS and backup stuff ..."
find . -name CVS -o -name .svn | xargs rm -rf
find . -name \*~ | xargs rm -f

echo "Compiling Java sources ..."
(cd src-java; make && make install && make clean; cd ..)

echo "$PNAME version ${VER}"
#cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
#mv d DESCRIPTION

# checks don't like src-java, use java instead
mv src-java java

echo "Creating package ..."
cd ..
R CMD build ${PNAME}
cd ${SWD}
cp /tmp/${PNAME}_${VER}.tar.gz ..
rm -rf /tmp/${PNAME}
echo "Done."
ls -l ../${PNAME}_${VER}.tar.gz
